//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compromplus_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikl
    {
        public Artikl()
        {
            this.StavkeDokumenta = new HashSet<StavkeDokumenta>();
            this.PracenjeProizvodnje = new HashSet<PracenjeProizvodnje>();
            this.stavkeIzdatnice = new HashSet<stavkeIzdatnice>();
            this.stavkeOtpremnice = new HashSet<stavkeOtpremnice>();
            this.stavkePrimke = new HashSet<stavkePrimke>();
        }
    
        public int IdArtikl { get; set; }
        public string naziv { get; set; }
        public string opis { get; set; }
        public string boja { get; set; }
        public Nullable<int> kolicina { get; set; }
        public string klasa { get; set; }
        public Nullable<int> barkod { get; set; }
        public Nullable<int> tip { get; set; }
    
        public virtual ICollection<StavkeDokumenta> StavkeDokumenta { get; set; }
        public virtual ICollection<PracenjeProizvodnje> PracenjeProizvodnje { get; set; }
        public virtual ICollection<stavkeIzdatnice> stavkeIzdatnice { get; set; }
        public virtual ICollection<stavkeOtpremnice> stavkeOtpremnice { get; set; }
        public virtual ICollection<stavkePrimke> stavkePrimke { get; set; }
    }
}
