//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compromplus_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narudzbenica
    {
        public int IdNarudzbenica { get; set; }
        public string naziv { get; set; }
        public string opis { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public int poslovniPart { get; set; }
        public int knjizDok { get; set; }
    
        public virtual KnjizenjeDokumenta KnjizenjeDokumenta { get; set; }
        public virtual poslovniPartner poslovniPartner { get; set; }
        public virtual stavkeNarudzbenice stavkeNarudzbenice { get; set; }
    }
}
