//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compromplus_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otpremnica
    {
        public Otpremnica()
        {
            this.stavkeOtpremnice = new HashSet<stavkeOtpremnice>();
        }
    
        public int IdOtpremnica { get; set; }
        public string naziv { get; set; }
        public string odrediste { get; set; }
        public Nullable<System.DateTime> datumOtpreme { get; set; }
        public string opis { get; set; }
        public int knjizenjeDok { get; set; }
        public int poslPartner { get; set; }
    
        public virtual KnjizenjeDokumenta KnjizenjeDokumenta { get; set; }
        public virtual poslovniPartner poslovniPartner { get; set; }
        public virtual ICollection<stavkeOtpremnice> stavkeOtpremnice { get; set; }
    }
}
