//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compromplus_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class StavkeDokumenta
    {
        public int artikl { get; set; }
        public int dokument { get; set; }
        public int kolicina { get; set; }
    
        public virtual Artikl Artikl1 { get; set; }
        public virtual Dokument Dokument1 { get; set; }
    }
}
