//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComPromPlusAplikacija
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipKorisnika
    {
        public tipKorisnika()
        {
            this.Korisnik = new HashSet<Korisnik>();
        }
    
        public int Id { get; set; }
        public string uloga { get; set; }
    
        public virtual ICollection<Korisnik> Korisnik { get; set; }
    }
}
