//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aplikacija
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dokument
    {
        public Dokument()
        {
            this.PoslovniPartner = new HashSet<PoslovniPartner>();
            this.stavke_dokumenta = new HashSet<stavke_dokumenta>();
        }
    
        public int IdDokument { get; set; }
        public string nazivArtikla { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public string opis { get; set; }
        public Nullable<int> tipDokumenta { get; set; }
    
        public virtual TipDokumenta TipDokumenta1 { get; set; }
        public virtual ICollection<PoslovniPartner> PoslovniPartner { get; set; }
        public virtual ICollection<stavke_dokumenta> stavke_dokumenta { get; set; }
    }
}
