//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aplikacija
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikli
    {
        public Artikli()
        {
            this.stavke_dokumenta = new HashSet<stavke_dokumenta>();
            this.stavke_repromaterijala = new HashSet<stavke_repromaterijala>();
        }
    
        public int IdArtikli { get; set; }
        public string naziv { get; set; }
        public string opis { get; set; }
        public string boja { get; set; }
        public Nullable<int> evidencijaKontrole { get; set; }
        public Nullable<int> kolicinaNaSkladistu { get; set; }
    
        public virtual ICollection<stavke_dokumenta> stavke_dokumenta { get; set; }
        public virtual ICollection<stavke_repromaterijala> stavke_repromaterijala { get; set; }
    }
}
