//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aplikacija
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class T28EnigmaEntities28 : DbContext
    {
        public T28EnigmaEntities28()
            : base("name=T28EnigmaEntities28")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Artikli> Artikli { get; set; }
        public DbSet<Djelatnik> Djelatnik { get; set; }
        public DbSet<Dokument> Dokument { get; set; }
        public DbSet<Korisnik> Korisnik { get; set; }
        public DbSet<Repromaterijal> Repromaterijal { get; set; }
        public DbSet<stavke_dokumenta> stavke_dokumenta { get; set; }
        public DbSet<stavke_repromaterijala> stavke_repromaterijala { get; set; }
        public DbSet<Stroj> Stroj { get; set; }
        public DbSet<TipDokumenta> TipDokumenta { get; set; }
        public DbSet<TipKorisnika> TipKorisnika { get; set; }
    }
}
