//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aplikacija
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repromaterijal
    {
        public Repromaterijal()
        {
            this.stavke_repromaterijala = new HashSet<stavke_repromaterijala>();
        }
    
        public int IdRepromaterijal { get; set; }
        public string vrsta_materijala { get; set; }
        public string boja { get; set; }
        public string opis { get; set; }
        public Nullable<int> kolicinaNaSkladistu { get; set; }
    
        public virtual ICollection<stavke_repromaterijala> stavke_repromaterijala { get; set; }
    }
}
