//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aplikacija
{
    using System;
    using System.Collections.Generic;
    
    public partial class stavke_repromaterijala
    {
        public int artikl { get; set; }
        public int repromaterijal { get; set; }
        public Nullable<int> kolicina { get; set; }
    
        public virtual Artikli Artikli { get; set; }
        public virtual Repromaterijal Repromaterijal1 { get; set; }
    }
}
