//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aplikacija
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipDokumenta
    {
        public TipDokumenta()
        {
            this.Dokument = new HashSet<Dokument>();
        }
    
        public int IdTipDokumenta { get; set; }
        public string naziv { get; set; }
    
        public virtual ICollection<Dokument> Dokument { get; set; }
    }
}
