//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComPromPlusAplikacija
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikli
    {
        public Artikli()
        {
            this.stavkeIzdatnice = new HashSet<stavkeIzdatnice>();
            this.stavkeOtpremnice = new HashSet<stavkeOtpremnice>();
            this.stavkePrimke = new HashSet<stavkePrimke>();
            this.Utrosak = new HashSet<Utrosak>();
        }
    
        public int Id { get; set; }
        public string naziv { get; set; }
        public string opis { get; set; }
        public string boja { get; set; }
        public Nullable<int> kolicina { get; set; }
        public string klasa { get; set; }
    
        public virtual ICollection<stavkeIzdatnice> stavkeIzdatnice { get; set; }
        public virtual ICollection<stavkeOtpremnice> stavkeOtpremnice { get; set; }
        public virtual ICollection<stavkePrimke> stavkePrimke { get; set; }
        public virtual ICollection<Utrosak> Utrosak { get; set; }
    }
}
