//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComPromPlusAplikacija
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class T23_Enigma2Entities : DbContext
    {
        public T23_Enigma2Entities()
            : base("name=T23_Enigma2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Artikli> Artikli { get; set; }
        public DbSet<Djelatnik> Djelatnik { get; set; }
        public DbSet<Izdatnica> Izdatnica { get; set; }
        public DbSet<knjizenjeDokumenta> knjizenjeDokumenta { get; set; }
        public DbSet<Korisnik> Korisnik { get; set; }
        public DbSet<Narudzbenica> Narudzbenica { get; set; }
        public DbSet<Otpremnica> Otpremnica { get; set; }
        public DbSet<poslovniPartner> poslovniPartner { get; set; }
        public DbSet<pracenjeProizvodnje> pracenjeProizvodnje { get; set; }
        public DbSet<Primka> Primka { get; set; }
        public DbSet<Repromaterijali> Repromaterijali { get; set; }
        public DbSet<stavkeIzdatnice> stavkeIzdatnice { get; set; }
        public DbSet<stavkeNarudzbenice> stavkeNarudzbenice { get; set; }
        public DbSet<stavkeOtpremnice> stavkeOtpremnice { get; set; }
        public DbSet<stavkePrimke> stavkePrimke { get; set; }
        public DbSet<Stroj> Stroj { get; set; }
        public DbSet<tipKorisnika> tipKorisnika { get; set; }
        public DbSet<Utrosak> Utrosak { get; set; }
    }
}
