//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPROMPlusdoo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Djelatnik
    {
        public Djelatnik()
        {
            this.pracenjeProizvodnje = new HashSet<pracenjeProizvodnje>();
        }
    
        public int Id { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string strucnaSprema { get; set; }
        public int stroj { get; set; }
        public string adresa { get; set; }
    
        public virtual Stroj Stroj1 { get; set; }
        public virtual ICollection<pracenjeProizvodnje> pracenjeProizvodnje { get; set; }
    }
}
