//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPROMPlusdoo
{
    using System;
    using System.Collections.Generic;
    
    public partial class knjizenjeDokumenta
    {
        public knjizenjeDokumenta()
        {
            this.Izdatnica = new HashSet<Izdatnica>();
            this.Narudzbenica = new HashSet<Narudzbenica>();
            this.Otpremnica = new HashSet<Otpremnica>();
            this.Primka = new HashSet<Primka>();
        }
    
        public int Id { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<Izdatnica> Izdatnica { get; set; }
        public virtual ICollection<Narudzbenica> Narudzbenica { get; set; }
        public virtual ICollection<Otpremnica> Otpremnica { get; set; }
        public virtual ICollection<Primka> Primka { get; set; }
    }
}
