//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPROMPlusdoo
{
    using System;
    using System.Collections.Generic;
    
    public partial class stavkeNarudzbenice
    {
        public Nullable<int> kolicina { get; set; }
        public int idNarudzbenice { get; set; }
        public int idRepromaterijala { get; set; }
    
        public virtual Narudzbenica Narudzbenica { get; set; }
        public virtual Repromaterijali Repromaterijali { get; set; }
    }
}
