//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPROMPlusdoo
{
    using System;
    using System.Collections.Generic;
    
    public partial class stavkePrimke
    {
        public int idArtikla { get; set; }
        public int idPrimke { get; set; }
        public Nullable<int> kolicina { get; set; }
    
        public virtual Artikli Artikli { get; set; }
        public virtual Primka Primka { get; set; }
    }
}
