//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compromplus_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnik
    {
        public int IdKorisnik { get; set; }
        public string korisnickoIme { get; set; }
        public string lozinka { get; set; }
        public Nullable<int> tipKorisnika { get; set; }
    
        public virtual TipKorisnika TipKorisnika1 { get; set; }
    }
}
