//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compromplus_app
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class T23_EnigmaEntities : DbContext
    {
        public T23_EnigmaEntities()
            : base("name=T23_EnigmaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Artikl> Artikl { get; set; }
        public DbSet<Djelatnik> Djelatnik { get; set; }
        public DbSet<Dokument> Dokument { get; set; }
        public DbSet<KnjizenjeDokumenta> KnjizenjeDokumenta { get; set; }
        public DbSet<Korisnik> Korisnik { get; set; }
        public DbSet<StavkeDokumenta> StavkeDokumenta { get; set; }
        public DbSet<Stroj> Stroj { get; set; }
        public DbSet<TipDokumenta> TipDokumenta { get; set; }
        public DbSet<TipKorisnika> TipKorisnika { get; set; }
        public DbSet<PracenjeProizvodnje> PracenjeProizvodnje { get; set; }
        public DbSet<Repromaterijali> Repromaterijali { get; set; }
        public DbSet<Utrosak> Utrosak { get; set; }
    }
}
