//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compromplus_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stroj
    {
        public Stroj()
        {
            this.PracenjeProizvodnje = new HashSet<PracenjeProizvodnje>();
        }
    
        public int IdStroj { get; set; }
        public string naziv { get; set; }
    
        public virtual ICollection<PracenjeProizvodnje> PracenjeProizvodnje { get; set; }
    }
}
