//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compromplus_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class PracenjeProizvodnje
    {
        public int IdPracenjeProizvodnje { get; set; }
        public Nullable<int> kolicina { get; set; }
        public Nullable<int> velicina { get; set; }
        public Nullable<int> IdArtikl { get; set; }
        public Nullable<int> IdDjelatnici { get; set; }
        public Nullable<int> IdStroj { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
    
        public virtual Artikl Artikl { get; set; }
        public virtual Djelatnik Djelatnik { get; set; }
        public virtual Stroj Stroj { get; set; }
    }
}
